name: Odśwież kalendarze

on:
  workflow_dispatch:
    

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: |
        pip3 install bs4
        pip3 install requests
        pip3 install icalendar
        pip3 install dateparser
    - run: python3 scripts/calendars.py
    - run: git add *
    - run: |
          git config --global user.name 'gh-bot'
          git config --global user.email 'marcinvaadin@users.noreply.github.com'
          git commit -am "Calendars refresh"
          git push
