name: Odśwież kalendarze

on:
  workflow_dispatch:
    

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4.0.3
    - run: npm install
    - run: npm run build
