name: Odśwież kalendarze

on:
  workflow_dispatch:
    

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: |
        pip3 install beatufilsoup4
        pip3 install requests
        pip3 install icalendar
        pip3 install dateparser
    - run: python3 scripts/calendars.py
    - run: git status
