name: Refresh calendars

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install Python packages
      run: |
        pip3 install bs4
        pip3 install requests
        pip3 install icalendar
        pip3 install dateparser
    - run: python3 scripts/calendars.py
    - name: Commit & push
      run: |
          git add *
          git config --global user.name 'gh-bot'
          git config --global user.email 'gh-bot@users.noreply.github.com'
          git commit -am "Calendars refresh"
          git push
