name: Run Synergia only

on:
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Install Node packages
      run: npm install
    - run: npm run synergia
